id: IF6A9FBEF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:21:32+00:00'
last_modified: '2022-06-10T05:47:58.899112+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20768
  title: 'མཁས་འཇུག་གི་མཆན་འགྲེལ་ལེགས་བཤད་སྣང་བའི་འོད་ཟེར་རལ་གྲི་དང་ཨུཏྤལའི་སྐོར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BB43:
      image_group_id: I8LS20831
      title: Volume 1 of mkhas 'jug gi mchan 'grel legs bshad snang ba'i 'od zer ral
        gri dang uta+pala'i skor/
      total_pages: 516
      order: 1
      base_file: BB43.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
